window.CRM_DESIGN = (() => {
  const products=['Amaranth10','Amaranth10 Cloud','Bizbox Alpha','Bizbox Alpha Cloud','ERP 10','iCUBE','iCUBE G20','iU','OmniEsol','PMS','SI(개발)','Smart A','Smart A Cloud','WEHAGO','WEHAGO T'];
  const owners=['user_1','user_2','user_3'];
  const statuses=['미진행','진행','이월','계약완료','영업종료'];
  const institutionTypes=['일반기업','비영리법인','비영리단체','공공기관','학교·교육기관','기타'];
  const outcome=['연결됨','부재/미응답','관심 확인','견적 전달','미팅 확정','계약 성사','실주','기타'];
  const f=(key,label,type='text',options,required=false)=>({key,label,type,options,required});
  const s=(key,label,options,required=false)=>f(key,label,'select',options,required);
  const g=(title,fields)=>({title,fields});
  const common=[f('q','고객사·코드·내용 검색','search'),s('owner','담당자',['전체',...owners])];
  const period=[f('from','시작일','date'),f('to','종료일','date')];
  const productFilter=s('product','제품',['전체',...products]);
  const customerForm=[g('고객 기본 정보',[f('name','고객사명','text',null,true),f('business','사업자등록번호','text',null,true),s('clientType','거래처유형',['신규','유지보수 체결','유지보수 미체결'],true),s('institution','기관유형',institutionTypes,true),s('owner','영업담당자',owners,true),s('status','영업진행상태',statuses)]),g('유입 · 사용 제품',[s('source','소스출처',['마케팅','영업부'],true),s('channel','인입경로',['홈페이지','전화','소개','방문','캠페인','기타'],true),f('products','현재제품','multi',products),f('previousProducts','이전제품','multi',products),f('modules','사용모듈'),s('newsEnabled','뉴스 스크래핑',['ON · 수집함','OFF · 수집 안 함'])]),g('연락 · 관리 정보',[f('contact','메인 담당자'),f('phone','연락처','tel'),f('email','이메일','email'),f('address','주소'),f('custom1','팀'),f('custom2','관리항목2'),f('custom3','관리항목3')])];
  const forecastForm=[g('고객 · 계약 정보',[s('company','고객사',[],true),s('owner','영업담당자',owners,true),s('dealType','계약 형태',['신규','업셀','추가'],true),f('products','품목','multi',products)]),g('금액 · 예정 일정',[f('license','라이선스 금액 (원)','number',null,true),f('education','교육비 (원)','number'),f('forecastMonth','포캐스팅 예정월','month',null,true),f('invoiceDate','계약 예정일','date'),s('status','계약 여부',['미계약','계약']),f('contractMonth','계약월','month')]),g('이월 관리',[f('carryoverMonth','이월 대상월','month'),f('carryoverReason','이월 사유','textarea')])];
  const forecastFilters=[f('fromMonth','시작월','month'),f('toMonth','종료월','month'),s('owner','담당자',['전체',...owners])];
  const forecastExtra=[s('period','빠른 선택',['이번 달','최근 3개월','올해','직접 선택']),s('basis','표시 기준',['라이선스','교육비','총액']),s('team','팀',['전체','전략사업본부','마케팅본부']),f('contractFrom','계약 예정일 시작','date'),f('contractTo','계약 예정일 종료','date'),s('status','계약 여부',['전체','미계약','계약']),s('dealType','형태',['전체','신규','업셀','추가'])];
  const pages=[
    {id:'home',title:'대시보드',group:'워크스페이스',icon:'home',kind:'home',description:'오늘의 실행과 다음 영업 기회를 한눈에 확인하세요.',source:'/pages/member/dashboard/index.php',filters:[s('scope','조회 범위',['개인','팀','전체']),s('inactive','미활동 기준',['7일 이상','14일 이상','30일 이상','45일 이상','60일 이상','90일 이상','120일 이상','180일 이상','365일 이상'])],extra:[s('status','영업상태',['전체',...statuses]),s('clientType','고객유형',['전체','신규','유지보수 체결','유지보수 미체결']),productFilter]},
    {id:'customers',title:'고객사 관리',group:'고객 관리',icon:'users',kind:'list',entity:'customers',description:'고객 정보와 담당자, 영업 이력을 한곳에서 관리하세요.',source:'/pages/member/customer/company_list.php',filters:[f('q','거래처명·코드 검색','search'),f('business','사업자등록번호'),s('owner','영업담당자',['전체',...owners])],extra:[s('clientType','거래처유형',['전체','유지보수 체결','유지보수 미체결','신규']),s('institution','기관유형',['전체',...institutionTypes]),productFilter,s('team','팀',['전체','전략사업본부','마케팅본부']),f('custom2','관리항목2'),f('custom3','관리항목3'),s('market','상장시장',['전체','코스피','코스닥','코넥스','기타']),s('listed','상장상태',['전체','상장','비상장','미확인'])],columns:['고객사','사업자등록번호','기관유형','현재제품','영업담당자','영업진행상태','최근 활동','거래처유형','연락처','이메일','주소','이전제품','사용모듈','소스출처','인입경로','팀','관리항목2','관리항목3'],form:customerForm,primary:'고객사 추가'},
    {id:'nonprofits',title:'비영리 관리',group:'고객 관리',icon:'users',kind:'list',entity:'nonprofits',description:'설립 단계와 예산 편성 일정을 고객 기록과 함께 확인하세요.',source:'/pages/member/customer/nonprofit_management.php',filters:common,extra:[s('stage','설립단계',['전체','설립방침 수립','타당성 검토 준비','1차 협의','타당성 검토 시행','2차 협의','설립 승인','기관 설립']),s('budget','예산편성여부',['전체','미편성','편성 예정','편성 완료']),f('establishmentMonth','설립시기','month'),productFilter],columns:['기관명','설립단계','설립시기','예산편성여부','예산편성시기','영업담당자','알림주기','기관유형','연계 뉴스','최근 활동','거래처유형','소스출처','인입경로','사업자등록번호'],form:[...customerForm,g('설립 · 예산 관리',[s('stage','설립단계',['설립방침 수립','타당성 검토 준비','1차 협의','타당성 검토 시행','2차 협의','설립 승인','기관 설립'],true),f('establishmentMonth','설립시기','month'),s('budget','예산편성여부',['미편성','편성 예정','편성 완료'],true),f('budgetMonth','예산편성시기','month'),f('reminderDays','알림주기 (일)','number',null,true)])],primary:'기관 등록'},
    {id:'news',title:'영리·비영리 뉴스',group:'고객 관리',icon:'file',kind:'news',description:'고객과 연결된 소식에서 새로운 영업 기회를 찾으세요.',source:'/pages/member/customer/nonprofit_news.php',filters:[f('q','기사 제목·내용·언론사','search'),s('source','뉴스 출처',['전체','NAVER','Google']),s('scope','조회 범위',['전체 고객사','내 담당 고객사','관심 고객사'])],extra:[s('company','연계 고객사',['전체']),...period,s('sort','정렬',['최신순','오래된순','중요 리드순']),f('unread','미확인만','checkbox'),f('important','중요 리드만','checkbox'),f('group','기사 묶기','checkbox')]},
    {id:'contacts',title:'컨택 관리',group:'고객 관리',icon:'users',kind:'list',entity:'contacts',description:'고객사 담당자와 연락 이력, 이직 정보를 연결해 관리하세요.',source:'/pages/member/contact/contact_main.php',filters:[f('q','담당자·회사명 검색','search'),f('phone','연락처'),f('email','이메일')],extra:[f('contact','담당자 이름'),f('company','회사명'),f('business','사업자번호')],columns:['담당자명','회사명','부서','직책','연락처','이메일','메인 담당자','담당자코드','사업자번호','재직 상태'],form:[g('소속 · 담당자 정보',[s('company','회사명',[],true),f('name','담당자명','text',null,true),f('department','부서'),f('position','직책'),f('phone','연락처','tel'),f('email','이메일','email'),f('primary','메인 담당자','checkbox')]),g('연락 관리',[f('memo','비고','textarea')])],primary:'담당자 추가'},
    {id:'upload',title:'고객사 일괄업로드',group:'고객 관리',icon:'file',kind:'upload',entity:'customers',description:'파일 선택부터 검증, 반영 결과까지 단계별로 확인하세요.',source:'/pages/member/customer/company_excel_upload.php'},
    {id:'activity',title:'영업활동 관리',group:'영업 실행',icon:'activity',kind:'activity',description:'상담 내용을 기록하고 다음 행동으로 연결하세요.',source:'/pages/member/activity/activity_register.php'},
    {id:'tasks',title:'오늘의 업무함',group:'영업 실행',icon:'clock',kind:'tasks',entity:'tasks',description:'지금 해야 할 일부터 완료한 활동까지 빠짐없이 관리하세요.',source:'/pages/member/sales/task_board.php',filters:[f('q','업무·고객사 검색','search'),s('status','상태',['전체','진행','완료','취소']),s('range','기한',['전체','기한 경과','오늘','7일 내','오늘 완료'])],extra:[s('scope','조회 범위',['내 업무','전체 업무']),s('owner','담당자',['전체',...owners])],columns:['업무','고객사','마감일시','우선순위','유형','담당자','상태'],form:[g('업무 정보',[f('name','업무 제목','text',null,true),s('type','유형',['후속 연락','상담','자료 전달','계약 확인','일반 업무']),s('priority','우선순위',['보통','높음','긴급','낮음']),f('due','마감일시','datetime-local',null,true),s('owner','담당자',owners,true),s('company','고객사',[])]),g('설명',[f('content','업무 설명','textarea')])],primary:'새 업무'},
    {id:'leads',title:'통합 리드함',group:'영업 실행',icon:'users',kind:'list',entity:'leads',description:'새로운 문의를 배정하고 첫 연락을 업무로 연결하세요.',source:'/pages/member/sales/lead_inbox.php',filters:[f('q','회사·담당자·문의 검색','search'),s('status','상태',['전체','신규','접촉','유효','전환','제외','중복']),s('source','유입',['전체','홈페이지','마케팅','수동'])],extra:[s('scope','조회 범위',['전체 리드','내 리드']),s('owner','담당자',['전체','미배정',...owners]),s('priority','우선순위',['전체','긴급','높음','보통','낮음'])],columns:['회사/담당자','유입일시','유입','우선순위','상태','담당자','응답기한','연락처','이메일','문의내용'],form:[g('고객 정보',[f('company','회사명','text',null,true),f('contact','담당자명'),f('phone','연락처','tel'),f('email','이메일','email'),s('owner','담당 영업사원',['미배정',...owners]),s('priority','우선순위',['보통','긴급','높음','낮음'])]),g('문의 · 진행',[f('content','문의내용','textarea',null,true),s('source','유입',['수동','홈페이지','마케팅']),s('status','상태',['신규','접촉','유효','전환','제외','중복'])])],primary:'리드 등록'},
    {id:'quotes',title:'견적 현황',group:'영업 실행',icon:'file',kind:'analytics-list',entity:'quotes',description:'제안 금액과 고객 반응을 함께 확인하고 후속 상담을 이어가세요.',source:'/pages/member/activity/quote_status.php',filters:[...period,s('owner','담당자',['전체',...owners])],extra:[f('q','통합검색','search'),s('type','접촉유형',['전체','TM','메일','방문']),s('status','상태',['전체','제안','검토','계약','실주']),s('sort','정렬',['최신순','금액 높은순','고객사명순'])],columns:['거래처','견적일시','제품','견적총액','상태','담당자','고객사 담당자','접촉유형','제목 / 내용','라이선스','교육비','첨부'],form:[g('고객 · 견적',[s('company','거래처',[],true),s('owner','담당자',owners),f('contact','고객사 담당자'),f('date','견적일시','datetime-local',null,true),s('type','접촉유형',['TM','메일','방문']),f('products','제품','multi',products)]),g('금액 · 내용',[f('license','라이선스 (원)','number',null,true),f('education','교육비 (원)','number'),s('status','상태',['제안','검토','계약','실주']),f('name','제목'),f('content','내용','textarea'),f('attachments','견적서 첨부','file')])],primary:'견적 등록'},
    {id:'marketing',title:'마케팅 활동',group:'영업 실행',icon:'activity',kind:'list',entity:'marketing',description:'신규 고객의 반응과 마케팅 활동을 영업 기록으로 연결하세요.',source:'/pages/member/marketing/marketing_activity_register.php',filters:[f('q','거래처·코드·내용 검색','search'),s('source','소스출처',['전체','마케팅','영업부']),s('owner','입력자',['전체',...owners])],extra:[...period,s('customerType','고객 구분',['전체','기존 고객','신규 고객']),s('channel','마케팅 채널',['전체','메일','전화','온라인','행사']),s('type','활동 유형',['전체','캠페인','홍보','상담','자료 전달'])],columns:['대상 고객','활동일','마케팅 채널','활동 유형','리드 단계','리드 점수','입력자','제목','연계 영업활동','관심 품목'],form:[g('대상 고객',[s('customerType','고객 구분',['기존 고객','신규 고객']),s('company','기존 고객사',[]),f('newCompany','신규 회사명'),f('business','신규 사업자번호'),f('contact','신규 담당자'),f('phone','신규 연락처','tel'),f('email','신규 이메일','email')]),g('활동 정보',[s('owner','입력자',owners),s('channel','마케팅 채널',['메일','전화','온라인','행사']),s('type','활동 유형',['캠페인','홍보','상담','자료 전달']),f('date','활동일','datetime-local',null,true),f('name','제목','text',null,true),f('products','관심 품목','multi',products),s('linkedActivity','연계 영업활동',['미연계','도입 제안 상담','제품 시연'])]),g('내용 · 리드',[f('content','활동 내용','textarea',null,true),s('stage','리드 단계',['신규','관심','상담','유효','전환']),f('score','리드 점수 (0–100)','number'),f('attachments','첨부파일','file')])],primary:'마케팅 활동 등록'},
    {id:'yearly',title:'연간 영업현황',group:'분석 · 보고',icon:'chart',kind:'analytics-list',entity:'activities',description:'활동 추이와 담당자별 성과를 같은 기준으로 비교하세요.',source:'/pages/member/activity/activity_year.php?year=2026',filters:[s('year','연도',['2026','2025','2024']),...period],extra:[s('owner','영업담당자',['전체',...owners]),s('type','활동유형',['전체','TM','메일','방문','견적']),s('subtype','상세유형',['전체','제안서','견적','상담','심화PT','TM(in)','TM(out)','유지보수','추가계약']),f('mine','나만 보기','checkbox'),f('all','전체 목록 보기','checkbox')],columns:['고객사','활동일시','담당자','활동명','활동유형','상세유형','리드타임']},
    {id:'activity-detail',title:'활동별 업체별 현황',group:'분석 · 보고',icon:'chart',kind:'analytics-list',entity:'activities',description:'활동 유형과 거래처별 기록을 필터로 좁혀 확인하세요.',source:'/pages/member/activity/activity_detail_status.php',filters:[...period,s('owner','담당자',['전체',...owners])],extra:[s('type','활동유형',['전체','TM','메일','방문','견적']),s('subtype','세부유형',['전체','제안서','견적','상담','심화PT','TM(in)','TM(out)','유지보수','추가계약']),s('status','상태',['전체',...outcome]),f('forecastOnly','포캐스팅 등록업체만','checkbox')],columns:['거래처','활동일시','담당자','유형','세부유형','제목','상태','라이선스','교육비','총액']},
    {id:'ai',title:'IONE AI',group:'분석 · 보고',icon:'spark',kind:'ai',description:'고객 기록을 바탕으로 다음 상담의 우선순위를 확인하세요.',source:'/pages/member/activity/ione_ai.php',filters:[...period,s('scope','범위',['개인','팀','전체'])]},
    {id:'work-report',title:'업무일지',group:'분석 · 보고',icon:'file',kind:'work-report',entity:'activities',columns:['고객사','활동일시','담당자','활동명','유형','상태','총액'],description:'활동 기록과 포캐스팅을 모아 하루의 업무를 정리하세요.',source:'/pages/member/report/work_report.php',filters:[...period,s('owner','담당자',['전체',...owners])],extra:[f('q','제목·내용 검색','search'),s('type','영업활동',['전체','TM','메일','방문','견적']),s('subtype','세부활동',['전체','제안서','상담','심화PT','유지보수','추가계약']),s('basis','금액 유형',['라이선스','교육비','총액'])]},
    {id:'custom-reports',title:'사용자 정의 보고서',group:'분석 · 보고',icon:'chart',kind:'report-builder',description:'분석 기준을 선택하고 결과를 바로 확인하세요.',source:'/pages/member/report/custom_reports.php'},
    {id:'ssl-master',title:'SSL 기초정보 관리',group:'SSL · 계약',icon:'shield',kind:'master',description:'매입처, 인증서 품목, 갱신주기를 같은 기준으로 관리하세요.',source:'/pages/member/contract/ssl_master.php'},
    {id:'ssl-purchase',title:'SSL 매입 관리',group:'SSL · 계약',icon:'shield',kind:'list',entity:'sslPurchase',description:'발주 정보를 등록하고 품목별 매입 금액을 확인하세요.',source:'/pages/member/contract/ssl_purchase.php',filters:[...period,s('supplier','매입처',['전체','파트너 A','파트너 B'])],extra:[f('q','발주명·번호·고객사 검색','search'),s('status','진행상태',['전체','발주','입고','취소'])],columns:['발주명','발주번호','발주일','매입처','합계액','진행상태','납기예정일','발주 품목','공급가액','부가세'],form:[g('발주 정보',[f('name','발주명','text',null,true),s('supplier','매입처',['파트너 A','파트너 B'],true),f('date','발주일','date',null,true),f('deliveryDate','납기예정일','date'),f('content','발주 메모','textarea')]),g('품목별 발주',[f('items','발주 품목','line-items')])],primary:'발주 등록'},
    {id:'ssl-delivery',title:'SSL 출고 관리',group:'SSL · 계약',icon:'shield',kind:'list',entity:'sslDelivery',description:'설치·출고 상태와 인증서 정보를 고객별로 확인하세요.',source:'/pages/member/contract/ssl_delivery.php',filters:[f('from','설치 시작일','date'),f('to','설치 종료일','date'),s('supplier','매입처',['전체','파트너 A','파트너 B'])],extra:[s('expiration','만료구분',['전체','유효','30일 내 만료','만료']),f('q','고객사·도메인·인증서 검색','search')],columns:['고객사','SSL 품목','설치일','만료일','잔여일','출고상태','영업담당자','발주번호','발주명','매입처','도메인 용도','수량','출고 금액','인증서번호','출고 메모','만료상태'],form:[g('설치 · 인증서 정보',[s('company','고객사',[]),f('date','설치일','date'),f('expirationDate','만료일','date'),f('certificate','인증서번호'),s('status','출고상태',['출고','반품']),f('content','출고 메모','textarea')])],primary:'출고 정보 등록'},
    {id:'ssl-expiration',title:'SSL 만료·갱신 관리',group:'SSL · 계약',icon:'shield',kind:'list',entity:'sslExpiration',description:'다가오는 만료와 갱신 대상을 먼저 확인하세요.',source:'/pages/member/contract/ssl_expiration.php',filters:[s('range','알림구간',['전체','만료','7일 내','30일 내','90일 내']),s('supplier','매입처',['전체','파트너 A','파트너 B']),f('q','고객사·도메인 검색','search')],extra:[s('status','알림상태',['전체','미확인','확인']),s('basis','관리 기준',['인증서 만료','갱신 예정'])],columns:['고객사','도메인 용도','만료일','잔여일','알림구간','알림상태','영업담당자','갱신예정일','매입처','SSL 품목','갱신주기','발주번호','발주명','수량','인증서번호'],primary:'갱신 대상 확인'},
    {id:'forecast-add',title:'포캐스팅 등록',group:'포캐스팅',icon:'chart',kind:'form',entity:'forecasts',description:'고객, 예상 금액과 계약 일정을 함께 기록하세요.',source:'/pages/member/forecast/forecast_add.php',form:forecastForm},
    {id:'forecast-status',title:'포캐스팅 현황',group:'포캐스팅',icon:'chart',kind:'forecast',entity:'forecasts',description:'계약 예정과 이월, 목표 달성 현황을 같은 화면에서 확인하세요.',source:'/pages/member/forecast/forecast_status.php',filters:forecastFilters,extra:forecastExtra,columns:['거래처','담당자','라이선스','교육비','총액','계약예정일','계약여부','계약 형태','포캐스팅 예정월','이월원월','이월사유','대체'],form:forecastForm,primary:'포캐스팅 등록'},
    {id:'other-add',title:'기타계약 포캐스팅 등록',group:'포캐스팅',icon:'chart',kind:'form',entity:'otherForecasts',description:'기타계약의 예상 금액과 계약 일정을 기록하세요.',source:'/pages/member/other_contract/forecast_add_other.php',form:forecastForm},
    {id:'other-status',title:'기타계약 포캐스팅 현황',group:'포캐스팅',icon:'chart',kind:'forecast',entity:'otherForecasts',description:'기타계약의 계약 예정과 이월 현황을 확인하세요.',source:'/pages/member/other_contract/forecast_status_other.php',filters:forecastFilters,extra:forecastExtra,columns:['거래처','담당자','라이선스','교육비','총액','계약예정일','계약여부','계약 형태','포캐스팅 예정월','이월원월','이월사유','대체'],form:forecastForm,primary:'기타계약 등록'},
    {id:'admin',title:'관리자 대시보드',group:'관리자',icon:'settings',kind:'admin',description:'운영 설정과 기준정보를 업무별로 찾아 관리하세요.',source:'/pages/admin/dashboard.php'},
    {id:'members',title:'회원·담당업무 관리',group:'계정 · 조직',admin:true,kind:'list',entity:'members',description:'회원 정보와 담당 업무, 재직 상태를 함께 확인하세요.',source:'/pages/admin/members.php',filters:[f('q','이름·로그인 ID 검색','search')],columns:['이름','로그인 ID','직급','부서','권한','담당업무','재직 상태','퇴사일'],form:[g('회원 정보',[f('name','이름','text',null,true),f('loginId','로그인 ID','text',null,true),f('position','직급'),s('department','부서',['전략사업본부','마케팅본부']),s('role','권한',['사용자','관리자']),s('work','담당업무',['영업','마케팅','운영']),f('retirementDate','퇴사일','date')])],primary:'담당업무 관리'},
    {id:'transfer',title:'고객사 담당자 이관',group:'계정 · 조직',admin:true,kind:'transfer',entity:'customers',description:'대상 고객과 변경 전·후 담당자를 비교하고 이관하세요.',source:'/pages/admin/company_sales_rep_transfer.php',filters:[s('owner','기존 담당자',['전체','미배정',...owners]),f('q','고객사 검색','search')],columns:['고객사','사업자등록번호','고객코드','거래처유형','영업상태','현재 담당자','새 담당자']},
    {id:'permissions',title:'페이지 접근 권한',group:'계정 · 조직',admin:true,kind:'permissions',description:'페이지와 사용자 권한을 하나의 관리 흐름으로 정리하세요.',source:'/pages/admin/roles.php'},
    {id:'departments',title:'부서 관리',group:'계정 · 조직',admin:true,kind:'list',entity:'departments',description:'부서와 소속 인원을 한눈에 확인하세요.',source:'/pages/admin/departments.php',filters:[f('q','부서 검색','search')],columns:['부서명','소속 회원','등록일','상태'],form:[g('부서 정보',[f('name','부서명','text',null,true)])],primary:'부서 등록'},
    {id:'department-add',title:'부서 신규 등록',group:'계정 · 조직',admin:true,kind:'form',entity:'departments',description:'새 부서를 등록하고 조직 목록으로 연결하세요.',source:'/pages/admin/department_add.php',form:[g('부서 정보',[f('name','부서명','text',null,true)])]},
    {id:'goals',title:'매출 목표 관리',group:'계정 · 조직',admin:true,kind:'goals',description:'사원별 월 목표와 연간 합계를 함께 확인하세요.',source:'/pages/admin/goal/goal_list.php'},
    {id:'manage-items',title:'관리항목 관리',group:'기준정보',admin:true,kind:'manage-items',description:'고객 관리에 사용하는 항목 이름과 선택값을 관리하세요.',source:'/pages/admin/manage_items.php'},
    {id:'institutions',title:'기관유형 관리',group:'기준정보',admin:true,kind:'list',entity:'institutions',description:'기관유형별 사용 현황을 확인하고 선택 항목을 관리하세요.',source:'/pages/admin/institution_types.php',columns:['기관유형명','사용 고객사','상태'],form:[g('기관유형',[f('name','기관유형명','text',null,true)])],primary:'기관유형 추가'},
    {id:'acquisition',title:'유입정보 관리',group:'기준정보',admin:true,kind:'list',entity:'acquisition',description:'소스출처와 인입경로의 연결 관계를 정리하세요.',source:'/pages/admin/company_acquisition_options.php',columns:['항목명','소스출처','유형','상태'],form:[g('유입정보',[f('name','항목명','text',null,true),s('type','유형',['소스출처','인입경로']),s('source','상위 소스출처',['마케팅','영업부'])])],primary:'항목 추가'},
    {id:'commercial-news',title:'영리 뉴스 관리',group:'기준정보',admin:true,kind:'list',entity:'commercialKeywords',description:'수집 대상과 검색 키워드를 구분해 관리하세요.',source:'/pages/admin/commercial_news_keywords.php',columns:['키워드','노출 순서','수집 사용','연결 기사','연결 기관'],form:[g('수집 키워드',[f('name','키워드','text',null,true),f('order','노출 순서','number'),f('enabled','수집 사용','checkbox'),s('type','키워드 유형',['일반 키워드','고객사 연계 키워드'])])],primary:'키워드 추가'},
    {id:'nonprofit-keywords',title:'비영리 뉴스 키워드',group:'기준정보',admin:true,kind:'list',entity:'nonprofitKeywords',description:'기관 설립·예산 소식을 찾는 키워드를 관리하세요.',source:'/pages/admin/nonprofit_news_keywords.php',columns:['키워드','노출 순서','수집 사용','연결 기사','연결 기관'],form:[g('수집 키워드',[f('name','키워드','text',null,true),f('order','노출 순서','number'),f('enabled','수집 사용','checkbox'),s('type','키워드 유형',['일반 키워드','고객사 연계 키워드'])])],primary:'키워드 추가'},
    {id:'products',title:'품목 관리',group:'기준정보',admin:true,kind:'list',entity:'products',description:'판매 품목과 코드를 확인하고 활성 상태를 관리하세요.',source:'/pages/admin/products.php',filters:[f('q','품목명·코드 검색','search')],columns:['품목명','품목코드','상태','옵션 수'],form:[g('품목 정보',[f('name','품목명','text',null,true),f('code','품목코드','text',null,true),s('status','상태',['활성','비활성'])])],primary:'품목 추가'},
    {id:'product-options',title:'품목옵션 관리',group:'기준정보',admin:true,kind:'list',entity:'productOptions',description:'품목별 옵션과 코드를 연결해 관리하세요.',source:'/pages/admin/product_options.php',filters:[s('product','품목',['전체',...products]),f('q','옵션명·코드 검색','search')],columns:['옵션명','품목','옵션코드','상태'],form:[g('옵션 정보',[s('product','품목',products,true),f('name','옵션명','text',null,true),f('code','옵션코드','text',null,true),s('status','상태',['활성','비활성'])])],primary:'옵션 추가'},
    {id:'options-upload',title:'품목옵션 일괄등록',group:'기준정보',admin:true,kind:'upload',entity:'productOptions',description:'옵션 파일을 검증하고 반영 대상을 확인하세요.',source:'/pages/admin/product_options_upload.php'},
    {id:'marketing-types',title:'마케팅 활동유형',group:'운영 설정',admin:true,kind:'list',entity:'marketingTypes',description:'마케팅 활동에 사용하는 공통 선택 항목을 관리하세요.',source:'/pages/admin/marketing_activity_options.php',columns:['활동유형명','상태','등록일'],form:[g('활동유형',[f('name','활동유형명','text',null,true)])],primary:'활동유형 추가'},
    {id:'work-settings',title:'업무일지 운영 설정',group:'운영 설정',admin:true,kind:'work-settings',description:'업무일지에 표시할 인원과 선보고 수신 대상을 구분하세요.',source:'/pages/admin/work_report.php'},
    {id:'system',title:'시스템·알림 설정',group:'운영 설정',admin:true,kind:'settings',description:'브랜드 이미지와 업무 알림 수신 정보를 관리하세요.',source:'/pages/admin/settings.php'},
    {id:'migration',title:'데이터 마이그레이션',group:'운영 설정',admin:true,kind:'migration',description:'이전 대상과 검증 결과를 단계별로 확인하는 제안 화면입니다.',source:'/pages/admin/migrate_clients.php',proposed:true},
    {id:'login',title:'로그인',group:'운영 설정',admin:true,kind:'login',description:'',source:'/pages/auth/login/login.php'}
  ];
  return {pages,products,owners,statuses,outcome,institutionTypes,f,s,g};
})();
